In [1]:
import cv2#importing cv2 library
import numpy as np#importing numpy library

## Step 1: -

### Displaying the grayscaled video

In [2]:
def framing(video):#defining a small function named"framing" with a parameter "i" that's supposed to be provided for reading the video
    fr = []#creating an empty list named fr
    fr_pre=[]#creating an empty list named fr_pre
    cap = cv2.VideoCapture(video)#reading the video file
    while (cap.isOpened()):#This command builds a loop to check if the data is still being read from the video
        ret,frame = cap.read()#reading the data tunnel,gives two output where one tells about presence of frames(here it's ret) & the other speaks frame data(here it's frame)
        if ret == True:#checking for presence of frames
            cv2.imshow("fbyf",frame)#displaying the frames
            grayed = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)#Converting the frames to Grayscale from BGR
            canned = cv2.Canny(grayed,320,320)#For extrating edges we use Canny Edge detection method
            fr.append(frame)#Appending the read frame
            fr_pre.append(canned)#Appending the edge extracted frames
            cv2.imshow("Grayed",grayed)#Displaying the original frames
            cv2.imshow("Canned",canned)#Displaying the edge detected frames
            k = cv2.waitKey(10) & 0XFF#this is an arrangement for displaying the video where the secs for which each frame needs to be displayed in given in the paranthesis
            if k == ord('q'):#pressing 'q' key will close the video
                break
        else:
            break
    cap.release()#Here we release the resoures
    cv2.destroyAllWindows()#Here we delete all the windows that were created during the program       
    return fr_pre,fr     #returning the frames received after the execution of function

In [3]:
frames,ogframes = framing("cnc_vol_kathecreadoracontenido_15_comisiones.mp4") #calling function framing & then extracting the images
cv2.destroyAllWindows() #This is to destroy the windows created

In [4]:
diff = []#creatin a list variable
for i in range(0,len(frames)-1):#defining the range
    print(frames[i],frames[i+1])#checking the frames presence
    diff.append(cv2.absdiff(frames[i],frames[i+1]))#appending the diff between frames to the list variable so we're supposed to get only the difference between frames

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

## Step 2: -

### Since each image is nothing but an array to a computer. So multiple images would simply mean bunch of multiple arrays.

In [5]:
#Each image has 3 arrays namely for R(Red),G(Green) & B(Blue) color defining the color of the image, we need to calculate the mean among those & hence we call it intra-array mean
np.mean(diff)#intra-array mean can be simply calculated using this

1.6330143886784512

In [6]:
mn = np.mean(diff)#This gives mean
st_d = np.std(diff)#This gives standard deviation
print(mn,st_d)#we check the mean & standard deviation

1.6330143886784512 20.340893124901655


## Step 3 : - Threshold calculation

In [7]:
a = 2#Setting a random value we can modify it to any value
ts = mn + (a * st_d)#defining the standard threshold value for the project/global threshold value
print('The threshold==>',ts)

The threshold==> 42.31480063848176


## Step 4 : - Extracting the frames

In [8]:
a_fr = []#Creating an empty list
for i in range(len(diff)):#Defining the for loop to be looped over all the frames obtained after finding the frames resulted from subtracting
    mn = np.mean(diff[i])#Calculating the mean for each frame
    st_d = np.std(diff[i])#Calculating the standard deviation for each frame
    fr_ts = mn + (4*st_d)#Finding the threshold values for each frame/image
    print(i,fr_ts)
    a_fr.append([i,fr_ts])#Appending the frame number & the threshold values

0 37.48629726044497
1 39.854706985886274
2 52.603568068824714
3 46.829897528142006
4 40.04160313353302
5 38.34091508707705
6 40.704953142407234
7 37.71195694189084
8 39.34117485763312
9 35.616322494963036
10 32.52091188270087
11 34.66654143758898
12 35.59468430677018
13 35.70993960648357
14 41.562996066290054
15 41.67444869614565
16 38.88060722531237
17 40.451076644766005
18 38.78785208895526
19 41.600179349348394
20 37.54112450369844
21 36.66127285431222
22 35.76024941402661
23 38.37444436669577
24 34.81431339597191
25 33.09142925525418
26 33.044901718240574
27 29.825828671062855
28 31.755351368311718
29 30.555033761488545
30 33.43836254042647
31 32.67818931242008
32 33.70577918925953
33 29.350155187857503
34 33.0759272058258
35 65.729955259771
36 33.35388331265748
37 33.26919381647757
38 32.92830090131248
39 30.08217346256488
40 34.777428073137756
41 32.84253569652712
42 30.747175976310764
43 32.323259890786716
44 33.56086929903821
45 30.513106576298686
46 30.14167923323892
47 32.386

In [9]:
imp_fr = []#Creating an empty list
for i,ac_tr in(a_fr):#Defining the loop on the list obtained from above code
    if ac_tr >= ts:#Comapring the threshold values to the standard threshold/global threshold values
        print(i,ac_tr)
        imp_fr.append([i,ac_tr])#Appending the list with the imp frames based on their index & the values

2 52.603568068824714
3 46.829897528142006
35 65.729955259771
49 43.00785772967825
59 133.3723732125988
60 61.53153893678835
61 59.99377613638253
62 45.87677143826385
63 50.972503658527266
64 59.010179642301715
65 61.33659036354787
66 64.90331862772719
67 65.52722994440036
68 65.99536297019634
69 55.731021593923984
70 54.22513461042266
71 59.92000753076579
72 60.71381730542433
73 59.97208863271334
74 59.155434139785406
75 60.842289415456534
76 59.36171585406637
77 53.7204923741421
78 51.88925063299977
79 57.64635413908141
80 60.44746846108405
81 62.39731724410714
82 64.81486263381063
83 82.71018427923694
84 87.16945467405515
85 86.84875446090446
86 91.87871553961537
87 89.63929925371258
88 92.30829577003462
89 91.4356508094605
90 87.99619087757719
91 87.75646237797213
92 87.7504610542794
93 87.44085466372414
94 86.9699077116048
95 81.96341599594372
96 83.88411643636208
97 83.6612895469511
98 77.04794956544637
99 77.03093278784637
100 79.84050337034496
101 137.74719600372424
102 161.0366

In [10]:
key_fr = []#Creating an empty list
for i,_ in imp_fr:#Defining the loop over the list obtained from above code
    key_fr.append(ogframes[i])#This extracts the frames based on the index of frames 
    print(diff[i],i)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 2
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 3
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 35
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 49
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 59
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 60
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 61
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 62
[[0 0 0 ... 0 0 0]

In [11]:
#This code helps to check how many frames are being extracted
for i in range(len(key_fr)):
    cv2.imshow('keys',key_fr[i])
    print("Frame no==>",i)
    k = cv2.waitKey(100) & 0xFF
    if k == ord('q'):
        break
cv2.destroyAllWindows()

Frame no==> 0
Frame no==> 1
Frame no==> 2
Frame no==> 3
Frame no==> 4
Frame no==> 5
Frame no==> 6
Frame no==> 7
Frame no==> 8
Frame no==> 9
Frame no==> 10
Frame no==> 11
Frame no==> 12
Frame no==> 13
Frame no==> 14
Frame no==> 15
Frame no==> 16
Frame no==> 17
Frame no==> 18
Frame no==> 19
Frame no==> 20
Frame no==> 21
Frame no==> 22
Frame no==> 23
Frame no==> 24
Frame no==> 25
Frame no==> 26
Frame no==> 27
Frame no==> 28
Frame no==> 29
Frame no==> 30
Frame no==> 31
Frame no==> 32
Frame no==> 33
Frame no==> 34
Frame no==> 35
Frame no==> 36
Frame no==> 37
Frame no==> 38
Frame no==> 39
Frame no==> 40
Frame no==> 41
Frame no==> 42
Frame no==> 43
Frame no==> 44
Frame no==> 45
Frame no==> 46
Frame no==> 47
Frame no==> 48
Frame no==> 49
Frame no==> 50
Frame no==> 51
Frame no==> 52
Frame no==> 53
Frame no==> 54
Frame no==> 55
Frame no==> 56
Frame no==> 57
Frame no==> 58
Frame no==> 59
Frame no==> 60
Frame no==> 61
Frame no==> 62
Frame no==> 63
Frame no==> 64
Frame no==> 65
Frame no==> 66
Frame

In [12]:
print(len(frames))
print(len(key_fr))

375
167


In [13]:
#This function helps in writing the key-frames to a folder
for i in range(len(key_fr)):
    cv2.imshow('diff',frames[i])
    cv2.imshow('keys',key_fr[i])
    name = 'data/img' + str(i) +'.jpg'
    cv2.imwrite(name,key_fr[i])#Mention preferred path
    k = cv2.waitKey(100) & 0xFF
    if k == ord('q'):
        break
cv2.destroyAllWindows()